<?php
$tablesExistQuery = mysqli_query($koneksi, "SHOW TABLES LIKE 't_ppdbregist'");
$t_ppdbregistTableExists = mysqli_num_rows($tablesExistQuery) > 0;
if (!$t_ppdbregistTableExists) {
    $sql = "CREATE TABLE IF NOT EXISTS `t_ppdbregist` (
       ppdbregist_id int(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
        tahunajaran_id int(10) DEFAULT NULL,
        ppdbjurusan_id int(10)  DEFAULT NULL,
        ppdbregist_number varchar(200)  DEFAULT NULL,
        ppdbregist_name varchar(200)  DEFAULT NULL,
        ppdbregist_gender varchar(10)  DEFAULT NULL,
        ppdbregist_tempat varchar(200)  DEFAULT NULL,
        ppdbregist_tgllahir text  DEFAULT NULL,
        ppdbregist_nisn varchar(20)  DEFAULT NULL,
        ppdbregist_nokk varchar(20)  DEFAULT NULL,
        ppdbregist_nik varchar(20)  DEFAULT NULL,
        ppdbregist_nohp varchar(20)  DEFAULT NULL,
        ppdbregist_anakke varchar(10)  DEFAULT NULL,
        ppdbregist_saudara varchar(10)  DEFAULT NULL,
        ppdbregist_hobi varchar(100)  DEFAULT NULL,
        ppdbregist_cita varchar(100)  DEFAULT NULL,
        ppdbregist_actived int(10)  DEFAULT NULL,
        password varchar(200)  DEFAULT NULL,
        ppdbregist_stt varchar(100)  DEFAULT NULL,
        ppdbregist_prov varchar(100)  DEFAULT NULL,
        ppdbregist_kota varchar(100)  DEFAULT NULL,
        ppdbregist_kec varchar(100)  DEFAULT NULL,
        ppdbregist_kel varchar(100)  DEFAULT NULL,
        ppdbregist_alamat text  DEFAULT NULL,
        ppdbregist_rt varchar(5)  DEFAULT NULL,
        ppdbregist_rw varchar(5)  DEFAULT NULL,
        ppdbregist_kodepos varchar(10)  DEFAULT NULL,
        ppdbregist_jarak varchar(100)  DEFAULT NULL,
        ppdbregist_transportasi varchar(100)  DEFAULT NULL,
        ppdbayah_status varchar(100)  DEFAULT NULL,
        ppdbayah_name varchar(225)  DEFAULT NULL,
        ppdbayah_wn varchar(100)  DEFAULT NULL,
        ppdbayah_nik varchar(100)  DEFAULT NULL,
        ppdbayah_tempat varchar(100)  DEFAULT NULL,
        ppdbayah_tgllahir date  DEFAULT NULL,
        ppdbayah_pekerjaan varchar(100)  DEFAULT NULL,
        ppdbayah_pendidikan varchar(100)  DEFAULT NULL,
        ppdbayah_penghasilan varchar(100)  DEFAULT NULL,
        ppdbayah_nohp varchar(100)  DEFAULT NULL,
        ppdbibu_status varchar(100)  DEFAULT NULL,
        ppdbibu_name varchar(225)  DEFAULT NULL,
        ppdbibu_wn varchar(100)  DEFAULT NULL,
        ppdbibu_nik varchar(100)  DEFAULT NULL,
        ppdbibu_tempat varchar(100)  DEFAULT NULL,
        ppdbibu_tgllahir date  DEFAULT NULL,
        ppdbibu_pekerjaan varchar(100)  DEFAULT NULL,
        ppdbibu_pendidikan varchar(100)  DEFAULT NULL,
        ppdbibu_penghasilan varchar(100)  DEFAULT NULL,
        ppdbibu_nohp varchar(100)  DEFAULT NULL,
        ppdbwali_name varchar(225)  DEFAULT NULL,
        ppdbwali_status varchar(100)  DEFAULT NULL,
        ppdbwali_wn varchar(100)  DEFAULT NULL,
        ppdbwali_nik varchar(100)  DEFAULT NULL,
        ppdbwali_tempat varchar(100)  DEFAULT NULL,
        ppdbwali_tgllahir date  DEFAULT NULL,
        ppdbwali_pekerjaan varchar(100)  DEFAULT NULL,
        ppdbwali_pendidikan varchar(100)  DEFAULT NULL,
        ppdbwali_penghasilan varchar(100)  DEFAULT NULL,
        ppdbwali_nohp varchar(100)  DEFAULT NULL,
        ppdbasal_jenjang varchar(100)  DEFAULT NULL,
        ppdbasal_status varchar(100)  DEFAULT NULL,
        ppdbasal_npsn varchar(100)  DEFAULT NULL,
        ppdbasal_sekolah varchar(225)  DEFAULT NULL,
        ppdbasal_kota varchar(225)  DEFAULT NULL,
        ppdbasal_tahun varchar(100)  DEFAULT NULL,
        ppdbasal_noujian varchar(225)  DEFAULT NULL,
        ppdbasal_noijazah varchar(225)  DEFAULT NULL,
        update_at date DEFAULT NULL
    )";
    if (mysqli_query($koneksi, $sql)) {
        echo "Data  tabel t_ppdbregist berhasil dibuat.";
    } else {
        echo "Error saat create t_ppdbregist: " . mysqli_error($koneksi);
    }
    echo '<br>';
}
